(defun move-line-down()
  (interactive)
  (kill-new "")
  (save-excursion
    (next-line)
    (if (= (point-max) (line-end-position))
	(progn
	  (end-of-line)
	  (newline)
	  (previous-line)))
    (kill-whole-line)
    (previous-line)
    (beginning-of-line)
    (yank))
  (if (= (point) (line-beginning-position))
      (next-line))
  (setq kill-ring (cdr kill-ring)))
(global-set-key (kbd "M-n") 'move-line-down)

(defun move-line-up()
  (interactive)
  (kill-new "")
  (save-excursion
    (previous-line)
    (kill-whole-line)
    (end-of-line)
    (if (= (point) (point-max))
	(newline)
      (next-line))
    (beginning-of-line)
    (yank)
    (setq kill-ring (cdr kill-ring))))
(global-set-key (kbd "M-p") 'move-line-up)

(defun copy-line-down()
  (interactive)
  (copy-line-up)
  (next-line))
(global-set-key (kbd "M-N") 'copy-line-down)

(defun copy-line-up()
  (interactive)
  (kill-new "")
  (save-excursion
    (kill-ring-save (line-beginning-position) (line-end-position))
    (end-of-line)
    (newline)
    (yank))
  (setq kill-ring (cdr kill-ring)))
(global-set-key (kbd "M-P") 'copy-line-up)

(provide 'copy-and-move-line)
